#!/bin/bash
useEmail=0
df -PkH | grep -vE '^Filesystem|tmpfs|cdrom|udev|cgmfs' | awk '{ print $5 " " $1 }' | while read output;
  do
      usep=$(echo "$output" | awk '{ print $1}' | cut -d'%' -f1  )
      partition=$(echo "$output" | awk '{ print $2 }' )
      if [ "${usep}" -ge 90 ]; then
          if [ "${useEmail}" -eq 1 ]; then
              echo "DISK ALERT: Partition '$partition' on $(hostname) is at $usep% capacity!" |
                  mail -s "DISK ALERT on $(hostname)" root@localhost
          else
              logger -p local3.error -t "diskfree-alert" "DISK ALERT: Partition '$partition' on $(hostname) is at $usep% capacity!"
          fi
      fi
  done
