<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutDir>$(SolutionDir)x64\$(Configuration)\</OutDir>
    <IntDir>$(SolutionDir)x64\$(Configuration)\Intermediate\</IntDir>
</PropertyGroup>

<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutDir>$(SolutionDir)x64\$(Configuration)\</OutDir>
    <IntDir>$(SolutionDir)x64\$(Configuration)\Intermediate\</IntDir>
</PropertyGroup> 