#!/bin/bash
IFS=$'\n'
cat <<EOF
{
        "first_match_only": true,
            "rewrite_rules": [
EOF
for l in $(cat country_codes.csv)
do
i=$(echo $l | cut -d ',' -f1)
n=$(echo $l | cut -d ',' -f2- | perl -pe 's/\s+$//g')
cat <<EOF
    {
      "match": {
        "field": "ut_destinationCountry",
        "value": "$i"
      },
      "tag": {
        "ut_destinationCountry": "$n"
      }
    },
EOF
done
cat <<EOF
  ]
}
EOF
