#!/bin/bash

# for Ubuntu < 18, you have to compile fio
# apt install libaio-dev
# git clone https://github.com/axboe/fio.git
# cd fio
# ./configure
# make
# make install

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
sudo dpkg -l fio 2>&1 | grep -q 'no packages found' && sudo apt install fio -y
docker_mount=$(sudo docker info 2>/dev/null | grep "Docker Root Dir" | awk -F': ' '{print $2}')
outfile="${HOME}/fio-4k-$(hostname)-$(date +%s).txt"

[[ -d "$docker_mount" ]] || docker_mount=$(pwd)

echo "Running test on $docker_mount, please wait..."
[[ "$1" = "j" ]] && {
  echo "Jakub's test"
  sudo fio --name TEST --eta-newline=5s --filename="$docker_mount/test" \
    --rw=randread --size=500m --io_size=10g --blocksize=4k \
    --ioengine=libaio --fsync=1 --iodepth=1 --direct=0 \
    --numjobs=1 --runtime=60 --group_reporting
  }

sudo fio --output="${outfile}" "${DIR}/tests/4ktest.fio"
echo "Completed, results stored in \"${outfile}\""

rm -f "$docker_mount/test"
