version: '3'
services:
    lzperl:
        container_name: lzperl
        build:
            context: .
        image: perl:6.13.0
        volumes:
            - ~/.ssh:/root/.ssh
networks:
  default:
    external:
      name: lz_main
