#!/bin/bash

while read rule
do
    logzilla rules remove "$rule"
done < <(logzilla rules list | awk '{print $1}' | grep -i 'watchguard')

for f in ../rules.d/*.json
do
    logzilla rules add "$f"
done
